apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-frontend
  template:
    metadata:
      labels:
        app: eshop-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/mdansevicius/sairen-atelier/frontend:dev-e2a46185d77d
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_APP_ENV
          value: "dev"