---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frontend-secrets
  namespace: eshop-dev
spec:
  encryptedData:
    STRIPE_SECRET_KEY: AgA/Ahflk8NlCYecGcyvb9aOuV0BINfL5KRKyMsASiNUav5J50c2yDmsCE815avqGX/h8B05vGT7SxbhE0BoU7uUcc76ReOtI7VZVxme0EWxd6mKC0H02H/usR9wAY0r+PXxxgYw2KluGtEaXQg7UrekWj3naGv3Uw1ySFujY0L9fib84xkwKnepq1qxVm2SLn9O8SJeE4mtmT2g0F+ZVgXlEdPsQ5dUt+Qq+rP5g+SmhfaSnAfoaaF8El4ZM5Pq7MNbKJra2ajzp31mNhVRXRg9+01gpB0MJLg/qcvK9AxT/zkVnih8i/PbVVh1CPIDPvZO3THlfF+eAvDk+JUdg0BifN6jXbjBQYxUoL+pYfSSUPAFLWejqKSMkNROhdTBpc/6R1FZVLyU2mZHcjeRO50GWAZnR2xOBvlhHq32R8cWBsaHW5y7N1L2AzPW4Bk5tG/MkHJl9J0Z1ewI0MAkC/GuQnjZqes/iz5wNTZu+BxDhnwl2j6LcSVzlHrMoKtCseeEa50vSPLaGKcz8AoBUi+Ddc+DUGcZ2BBdGLbAjUzHZ4iD15qYFUVnpnVAaElOUu09yUeY232109i/P/Od8Q548ffmNyJEbs+g+whIBCDQw1qHigyHfBS7JvjvXluRihyp0Z+e2QYnYZBzpCPxqUhotdRIkkS3JIDGNgXGK9fRsSjjvnpfoVRgWyk2g42khwKGTWZOuMuOd0KreE+aaVIZIGzTBroNfplPJnzZHwf1tjthaLRYr5iQUf2Yif1bKGhIW/BXtU8z0DR9Cw7kQEV/MTSAdvVujZax5s5B1xOGhLgU9uE7QvDe3vFjPlpH9IInzYAjtmvIcaZ4dg==
  template:
    metadata:
      creationTimestamp: null
      name: frontend-secrets
      namespace: eshop-dev