apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_NAME: "eshop"
  DB_USER: "eshop_prod_user"
  DB_PASS: "change-me-prod"
  STRIPE_SECRET_KEY: "change-me-prod"
